# Generated by Django 2.0 on 2022-05-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acticle',
            fields=[
                ('acticle_id', models.AutoField(primary_key=True, serialize=False)),
                ('acticle_title', models.TextField(max_length=100)),
                ('acticle_brief', models.TextField(max_length=200)),
                ('acticle_html', models.TextField()),
                ('acticle_publish_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
